name             'coniwa_php52'
maintainer       'Hisashi KOMINE'
maintainer_email 'hssh@hssh.jp'
license          'mit'
description      'Installs/Configures coniwa_php52'
long_description 'Installs/Configures coniwa_php52'
version          '0.1.0'
supports         'centos', '= 7.0'
